# docker-compose.yml
version: '3'
services:
  python_service:
    build:
      context: .
      dockerfile: dockerfile.python
      args:
        - BASE_IMAGE=python:3.12
        - APP_VERSION=2.0
    environment:
      - DEBUG=true
    image: bettergreat/python_web:2.5

  node_service:
    build:
      context: .
      dockerfile: dockerfile.node
      args:
        - BASE_IMAGE=node:22.4
        - APP_NAME=my-nodejs-app
    environment:
      - NODE_ENV=development
    image: bettergreat/node_web:2.5