# Use the latest official Python image
FROM python:latest

# Set the working directory in the container
WORKDIR /app

# Copy the Python script into the container
COPY app.py .

# Run the Python script when the container launches
CMD ["python", "app.py"]